
version: '3.7'

services:
  sparkifydb:
    image: postgres
    ports:
      - 5431:5432
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres_volume:/var/lib/postgresql/data/

volumes:
  postgres_volume: